### ISSUE TITLE
Issue installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by seannewcomb** [trailbot/client#9]
I'm trying to install the server agent, but I'm getting "1060 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14" when using npm install in the watcher directory on my servers.

I'm rather new with npm so I may be missing something.

An additional question I have is where exactly should the 'railbot_client.pub.asc' go on the server?

[npm-debug.txt](https://github.com/trailbot/client/files/438459/npm-debug.txt)

**Comment by aesedepece** [comment]
Hi @seannewcomb,

Judging by the debug information you provided, it seems to be a problem with the `pre-commit` package.

Actually, such package is not in use any more, so we have just dropped it from `package.json`. Please try again and confirm if solved. Sorry for the inconvenience. 

The `fsevents` warning is normal, nothing to worry about. It is simply a dependency of `chokidar` only for OSX systems, so it obviously fails to install on GNU/Linux.

Regarding `trailbot_client.pub.asc`, you are OK to save it where you prefer, but it is recommended to put it inside the watcher folder for convenience because it is the path that the setup wizard uses by default.

Thanks,
Adán

**Comment by seannewcomb** [comment]
Hello @aesedepece ,

Thanks for the fast reply! Pulling the new version from git it looks like I was able to install and setup like normal, thank you for the help! Should be good to close.

Thanks,
Sean
